# Generated by Django 2.2 on 2019-04-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='vegetable',
        ),
    ]
